ecommerceproject/cart/urls.py
from django.urls import path
from.import views

app_name='cart'

urlpatterns=[path('add/<int:product_id>/',views.add_cart,name='add_cart'),
             path('',views.cart_detail,name='cart_detail'),
             path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
             path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')]

ecommerceproject/ecommerceapp/urls.py
from.import views
from django.urls import path

app_name = 'ecommerceapp'


urlpatterns=[
              path('',views.allProdCat,name='allProdCat'),
              path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
              path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail')
             ]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ecommerceapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home'),
    path('ecommerceapp/',include('ecommerceapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.urls import path
from.import views

app_name="search_app"


urlpatterns=[path('',views.searchResult,name='searchResult')]

ecommerceproject/cart/models.py
from django.db import models
from ecommerceapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id

class  Cartitem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='Cartitem'
    def sub_total(self):
            return self.product.price * self.quantity

    def __str__(self):
            return self.product

ecommerceproject/ecommerceapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.



class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse("ecommerceapp:products_by_category",args=[self.slug])

    def __str__(self):
            return self.name
class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='product',blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse("ecommerceapp:ProdCatDetail", args=[self.category.slug,self.slug])

    def __str__(self):
            return self.name

ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Product
from.models import Cart,Cartitem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item=Cartitem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
            cart_item.save()
    except Cartitem.DoesNotExist:
        cart_item=Cartitem.objects.create(product=product,cart=cart,quantity=1)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=Cartitem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+= (cart_item.product.price * cart_item.quantity)
            counter+= cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=Cartitem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity-= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=Cartitem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/ecommerceapp/views.py
from django.http import HttpResponse
from.models import Category,Product
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
def home(request):
    return HttpResponse("helloo")

def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,3)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})


def ProdCatDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':product})

ecommerceproject/search_app/views.py
from django.shortcuts import render

from ecommerceapp.models import Product
from django.db.models import Q

# Create your views here.
def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains = query)|Q(desc__contains = query))
    return render(request,"search.html",{'query':query,'products':products})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static  'css/style/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/style/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Welcome to the cart store where u can but awesome items.
{% endblock %}
{% block title %}
       Cart--Shop Your Favourite !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart Is Empty
        </h1>
        <br>
        <p class="text-center">
            Please Click<a href="{% url 'ecommerceapp:allProdCat' %}">Here</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">Your Items:</th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    P_name:{{cart_item.product.name}}
                    <br>
                    P_ID:{{cart_item.product.id}}
                    <br>
                    Unit Price:{{cart_item.product.price}}
                    <br>
                    Qty:{{cart_item.quantity}} * ₹{{cart_item.product.price}}
                </td>
                <td>₹{{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>&nbsp;
                </td>
                {% endif %}
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom-thead">
            <tr>
                <th>CheckOut</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart item before proceeding with the order payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your total is <strong>₹{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-success btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div>
<br>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.desc|truncatewords:155}}
    {% else %}
        Welcome to the cart store where u can but awesome items.
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}--Shop cart
    {% else %}
        See Our Collections--Shop cart
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
               <p><a href="{% url 'ecommerceapp:allProdCat' %}"><b>COLLECTIONS:</b></a>{{category.name}}</p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{category.image.url}}"  alt="{{category.name}}">

</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify"><center>{{category.desc}}</center></p>
</div>
    {% else %}
        <div>
           <center><img class="my_image my_image_padding" src="{% static 'img/shopcart.jpg' %}" style="width:1500px;height:900px" alt=""></center>
        </div>
        <br>
<div>
    <h1 class="text-center my_title">PRODUCT COLLECTIONS:</h1>
    <p class="text-justify"><center><b>"SHOP CARNIVAL:ENJOY WITH THE COLOURS U LIKE"</b></center></p>
</div>
    {% endif %}
<div class="container">
    <div  class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 19rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" style="width:300px;height:300px" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
    <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
         </div>
    </div>

</div>
{% endblock %}

ecommerceproject/templates/footer.html
<div class="footer-navbar-fixed-bottom   my_footer">
    <p class="text-center">&copy;You can always find something you wish</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<div>
    <center><img src="{% static 'img/TQ.png' %}" alt=logo" ></center>
</div>

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" xmlns="http://www.w3.org/1999/html">
<!--  <a class="navbar-brand" href="#">Navbar</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">ALL CATEGORIES</a>
             {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
        {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="cart:cart_details"><i class="fas fa-shopping-cart">{{item_count}}</i></a>
      </li>
        {% endif %}
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">YOUR CART</a>-->
<!--      </li>-->
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

<!--<nav>-->
<!--    <ul>-->
<!--        <li><a href="{% url 'ecommerceapp:allProdCat' %}">ALL PRODUCTS</a> </li>-->
<!--        {% for cat in links %}-->
<!--            <li><a href="{{cat.get_url}}">{{cat.name}}</a> </li>-->
<!--        {% endfor %}-->
<!--        <li>YOUR CART</li>-->

<!--    </ul>-->
<!--</nav>-->

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{%  block title %}
    {{product.name}}--torque
{% endblock %}
{% block content %}
<div class="row my_prod_class">
    <div class="mx-auto">
        <p style="color: red"><a href="{% url 'ecommerceapp:allProdCat' %}">Home </a>|<a href="{{product.category.get_url}}"> </a>{{product.name}}</p>
    </div>
<div class="container">
<br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
             <div class="card text-center" style="width: 19rem;">
            <img src="{{product.image.url}}" style="width:400px; height:400px" alt="{{product.name}}">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title"><b>{{product.name}}</b></h1>
            <p>₹{{product.price}}</p>
            <p class="my_title"><b>Product Description</b></p>
            <p class="text-justify my_prod_text">{{product.desc}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>OUT OF STOCK</b></p>
            {% else %}
                <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">ADD CART</a>
            {% endif %}
        </div>
        </div>
      </div>
     </div>
</div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.desc|truncatewords:155}}
{% endblock %}
{%  block title %}
    {{product.name}}--torque
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:{{query}}</p>
</div>
<div class="container">
    <div  class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 19rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" style="width:300px;height:300px" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>₹{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
             <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
          </div>
</div>

{% endblock %}